# Generated by Django 5.0.2 on 2024-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='upload')),
                ('Priority', models.IntegerField(default=0)),
                ('Delete_status', models.IntegerField(choices=[(1, 'live'), (0, 'delete')], default='live')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Upadated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
