# Generated by Django 5.0.2 on 2024-03-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_prodect_category_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prodect',
        ),
    ]
