# Generated by Django 5.0.2 on 2024-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_prodect'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uplode/prodect/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
