# Generated by Django 5.0.2 on 2024-03-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_prodect_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodect',
            old_name='title',
            new_name='prodect_name',
        ),
    ]
