# Generated by Django 5.0.2 on 2024-03-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_title_prodect_prodect_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prodect',
        ),
    ]
