# Generated by Django 5.0.3 on 2024-03-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_type_product_dietary_choices_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dietary_choices',
            field=models.CharField(choices=[('V', 'Vegetarian'), ('N', 'Non-Vegetarian')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
