# Generated by Django 5.0.4 on 2024-04-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
