# Generated by Django 5.0.4 on 2024-04-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_restaurant_status_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_terms',
        ),
    ]
